GET http://localhost:4000

###

POST http://localhost:4000/signin HTTP/1.1
content-type: application/json

{
    "email" : "lanzoni.nicola@gmail.com",
    "password" : "mela"
}

###

POST http://localhost:4000/register
content-type: application/json

{
    "name": "Gustavo",
    "email" : "gustavo.bergamaschi@gmail.com",
    "password" : "pera"
}

###

GET http://localhost:4000/profile/123

###

POST http://localhost:4000/image
content-type: application/json

{
    "id": "123"
}