GET http://localhost:4000

###

GET http://localhost:4000/ping

###
GET https://face-recognition-api2020.herokuapp.com/ping

###

POST http://localhost:4000/signin HTTP/1.1
content-type: application/json

{
    "signInEmail" : "lanzoni.nicola@gmail.com",
    "signInPassword" : "mela"
}

###

POST http://localhost:4000/register
content-type: application/json

{
    "name": "Mdfddareaseeio",
    "email" : "mfd2aes4e3rio.rdossi@gmafidl.com",
    "password" : "pera"
}

###

GET http://localhost:4000/profile/123

###

POST http://localhost:4000/image
content-type: application/json

{
    "id": "123"
}